name: Bug Report
description: Report a bug in Pipelogiq
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: "Pipelogiq version (run `curl localhost:8080/version` or check git tag)"
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "Minimal steps to reproduce the issue"
      placeholder: |
        1. Start the stack with `make compose-up`
        2. Create a pipeline with ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What you expected to happen"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "What actually happened"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Relevant log output (redact secrets)"
      render: text

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Docker Compose (default stack)
        - Local Go + Docker infra
        - Custom deployment
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 15, Ubuntu 24.04, etc."
